replicaCount: 2

image:
  repository: saffirescale/go-web-app
  pullPolicy: IfNotPresent
  tag: "20483651007"

# service:
#   type: ClusterIP
#   port: 80
#   targetPort: 8080

# ingress:
#   enabled: true
#   className: nginx
#   annotations: {}
#   hosts:
#     - host: go-web-app.local
#       paths:
#         - path: /
#           pathType: Prefix
#   tls: []
